### PR TITLE
A bit of style

### PR DESCRIPTION
**Pull request by TheGiraffe3**
A little bit of style in the outfits and ships, plus a master merge.
~To be honest, I was expecting more style.~

### CODE REVIEW

**Comment by RisingLeaf** [comment]
sorry but I think this PR is broken, there are a lot of unrelated changes

**Comment by TheGiraffe3** [comment]
That's merging master in, but I see that you just did that for the branch.

**Comment by RisingLeaf** [comment]
I hope you are right.

**Comment by TheGiraffe3** [comment]
Yes, if you look at the commit details.

**Pull request merged**
